{
  try {
    closure.call(object);
    return true;
  }
 catch (  AssertionError e) {
    message=e.getMessage();
    return false;
  }
}
