{
  Range r=createRange(10,20);
  try {
    r.get(-1);
    fail("Should have thrown IndexOutOfBoundsException");
  }
 catch (  IndexOutOfBoundsException e) {
    assertTrue("expected exception thrown",true);
  }
  try {
    r.get(11);
    fail("Should have thrown IndexOutOfBoundsException");
  }
 catch (  IndexOutOfBoundsException e) {
    assertTrue("expected exception thrown",true);
  }
}
