{
  addError(new ExceptionMessage(cause));
  fail();
}
