{
  try {
    return method.invoke(object,argumentArray);
  }
 catch (  InvocationTargetException e) {
    Throwable t=e.getTargetException();
    if (t instanceof Error) {
      Error error=(Error)t;
      throw error;
    }
    throw new InvokerInvocationException(e);
  }
catch (  Exception e) {
    throw new InvokerException("failed to invoke method: " + method + " on: "+ object+ " with arguments: "+ InvokerHelper.toString(argumentArray)+ " reason: "+ e,e);
  }
}
