{
  try {
    new ObjectRange(createValue(23),null);
    fail("null 'to' accepted");
  }
 catch (  IllegalArgumentException e) {
    assertTrue("expected exception thrown",true);
  }
}
