{
  try {
    range.add(new Integer(12));
    fail("added value to empty range");
  }
 catch (  UnsupportedOperationException e) {
    assertTrue("expected exception thrown",true);
  }
}
