{
  boolean failed=false;
  try {
    code.call();
  }
 catch (  Exception e) {
    if (clazz.isInstance(e)) {
      failed=true;
    }
  }
  assertTrue("Closure " + code + " should have failed with an exception of type "+ clazz.getName(),failed);
}
