{
  try {
    new IntRange(2,1,true);
    fail("invalid range created");
  }
 catch (  IllegalArgumentException e) {
    assertTrue("expected exception thrown",true);
  }
}
