{
  super("Exception thrown by call to closure: " + closure + " reason: "+ cause,cause);
  this.closure=closure;
}
